# Generated by Django 6.0.3 on 2026-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(choices=[('compound', 'Compound'), ('hypertrophy', 'Hypertrophy')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('suggested_min_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suggested_max_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
